### ISSUE TITLE
피드백_ 맵 전체 광원 및 밝기 조절

### ISSUE THREAD

**Issue by bryanjang** [kookmin-sw/capstone-2024-21#141]

**Comment by youjin-43** [comment]
게임 메니저에서 메인 광원의 밝기 조절하는 함수 만들었는데 광원이 여러개 있을 수 있어서 함수를 따로 만들어야 함
밝기 0으로 만들어서 원하는 만큼 어둡지 않음

**Comment by youjin-43** [comment]
가능하면 안개도 해보기
