### ISSUE TITLE
아이템 스폰시 가끔 velocity 관련 오류가 뜸

### ISSUE THREAD

**Issue by youjin-43** [kookmin-sw/capstone-2024-21#64]
![image](https://github.com/kookmin-sw/capstone-2024-21/assets/150764368/6f0fb30c-3a8b-4cdb-8a84-ea1e66eda56d)

스폰 메커니즘을 조금 바꿔볼 예정

**Comment by youjin-43** [comment]
현재 아이템 스폰이 테이블에서 튀어나오는 형식. 그거떄문에 테이블이랑 끼면서 자꾸 오류뜨는 것 같음 -> 위에 기즈모 하나 달고 거기서 튀어나오게

**Comment by dydwo0809** [comment]
스포너의 위치에 따라서는 윗부분이 막혀있는 경우도 존재함

맵에서 스포너로 쓸만한 것들에 태그나 레이어 달아놓고 (+ 스폰 방향) 시작할 때 그중 몇개 랜덤으로 스포너로 만들 수도 있음
