### ISSUE TITLE
플레이어콜라이더 줄이기

### ISSUE THREAD

**Issue by youjin-43** [kookmin-sw/capstone-2024-21#68]
<img width="394" alt="스크린샷 2024-03-22 오후 12 00 02" src="https://github.com/kookmin-sw/capstone-2024-21/assets/150764368/b78a945f-5827-4132-893c-80ed2f8a2fff">

문을 안쪽으로 열리게 했더니 콜라이더에 끼어서 플레이어가 들어가지 못합니다 줄여야해요

**Comment by dydwo0809** [comment]
0.5 -> 0.3 변경
추후 세밀한 조정 필요
