### ISSUE TITLE
뒤통수 상호작용

### ISSUE THREAD

**Issue by youjin-43** [kookmin-sw/capstone-2024-21#84]
버츄얼 카메라에 달려서 그런지는 모르겠는데, 레이캐스트 시작점이 안바뀌는 문제 발생
그래서 캐릭터가 뒤통수로도 상호작용 하게 됩니다.

**Comment by youjin-43** [comment]
https://youtu.be/Bc5PyLruoDY?si=EcVqt8p11IcED8Bt

**Comment by dydwo0809** [comment]
해결 완료
