### ISSUE TITLE
퀵슬롯 버그

### ISSUE THREAD

**Issue by Noewewwwew** [kookmin-sw/capstone-2024-21#87]
현재 리스트 구조로 되어있어서 퀵슬롯에 넣어지는 아이템들이 자동으로 정렬되어 있습니다.
그래서 퀵슬롯이 비워져 있을 때 index를 받아오지 못하는 상황이 생겼고 그로 인해 아이템이 없을 때 1~5번으로 퀵슬롯에 접근을 하려 하면 오류가 발생한다.
또한 아이템을 하나만 획득하여 0번에 있는 아이템을 2번(다른 번호)로 옮겼을 때 아이템 아이콘은 옮겨지지만 실제로 아이템은 0번에 있으므로 2번으로 퀵슬롯이 접근을 하면 indexout 오류가 발생한다. 실제로 아이템이 있는 퀵슬롯 0번에 접근을 하면 아이콘이 0번에 있지 않아도 무기를 장착하는 버그가 발생한다.
요약 - 리스트 말고 배열로 만드는 것이 좋을 것 같다.

**Comment by youjin-43** [comment]
아이템 자리를 옮기는거 고려를 못했음 -> 아이템을 리스트 두개로 관리하는데 하나로 해서  일관되게 관리 되도록 해야할 것 같음

**Comment by youjin-43** [comment]
재원님께서 아이템을 가져올때 아이템 리스트가 아니라 ‘슬롯’에서 정보를 받아올 수 있도록 바꿈

206 라인에서
quickSlot.items[weaponIndex].ItemType

대신에
quickSlot.slots[idx].item.ItemType

이런식으로 아이템 정보 가져올 수 있도록 수정했습니다. 

만약 이렇게 해도 오류 해결이 안되면 그때는 갈아엎기로 함
